'use client'

import { useState, useCallback, useMemo, useEffect } from 'react'
import { motion } from 'framer-motion'

// 示例问题数据
const questions = {
    normal: [
        "When was the last time you got drunk?",
        "What's the craziest thing you've ever done?",
        "What's your biggest regret in life?",
        "Have you ever lied to your current friends?",
        "What's your most awkward dating experience?",
        "What's the most rebellious thing you've done?",
        "What's the worst gift you've ever received?",
        "What's a secret you'd never want your family to know?",
        "When was the last time you told a lie?",
        "What's your favorite movie and why?",
        "If you could redo one thing in your life, what would it be?",
        "What's your most memorable trip?",
        "Who's the person you're most grateful for?",
        "When was the last time you cried?",
        "What's your biggest dream in life?",
        "What's your favorite childhood memory?",
        "What's something you hate being told?",
        "What would you most like to change about yourself?",
        "When was the last time something touched your heart?",
        "What's your biggest source of stress?",
        "Why did you last pull an all-nighter?",
        "What's your favorite season and why?",
        "What moment in your life would you love to relive?",
        "What's your all-time favorite song?",
        "What skill would you most like to learn?",
        "What's your favorite dish?",
        "What's your most unforgettable birthday?",
        "Which teacher would you most like to thank?",
        "What's your favorite book?",
        "Where's the one place you'd love to visit?",
        "When was the last time you laughed out loud?",
        "What was your favorite childhood game?",
        "Which holiday would you love to experience again?",
        "What's your favorite season?",
        "What was your last pleasant surprise?",
        "Which date would you love to relive?",
        "What's your favorite TV show?",
        "What food would you love to try?",
        "When was the last time you worked out?",
        "Which trip would you love to take again?",
        "When was the last time you felt truly happy?",
        "What was your favorite childhood toy?",
        "Which class would you love to take again?",
        "What's your favorite holiday tradition?",
        "What recently moved you emotionally?",
        "Which family gathering would you love to relive?",
        "What's your favorite daily habit?",
        "What musical instrument would you love to learn?",
        "What's your most recent personal breakthrough?",
        "What's your favorite sport?",
        "Which performance would you love to see again?",
        "What's your favorite city?",
        "What was your last surprise?",
        "Which get-together would you love to experience again?",
        "What's your favorite way to relax?",
        "What new thing would you love to try?",
        "What's your most recent sense of achievement?",
        "What's your favorite holiday?",
        "Which adventure would you love to relive?",
        "What's your favorite dessert?",
        "What's your favorite life motto?",
        "Which friend would you most like to thank?",
        "When was the last time you did something kind?",
        "What's your favorite work experience?",
        "Which family trip would you love to take again?",
        "What's your favorite lifestyle habit?",
        "When was the last time you helped a stranger?",
        "What language would you love to learn?",
        "What's your favorite holiday?",
        "When was the last time someone complimented you?",
        "What hobby would you love to try?",
        "Who was your favorite childhood friend?",
        "What was your last dream about?",
        "What habit would you most like to change?",
        "What's your ideal work environment?",
        "What do you do when you're alone?",
        "What's your next small goal?",
        "What's your favorite way to rest?",
        "Why did you last wake up early?",
        "What pet would you love to have?",
        "What's your favorite holiday activity?",
        "What was your last impulse purchase?",
        "What landmark would you love to visit?",
        "What's your favorite type of exercise?",
        "What made you angry recently?",
        "What personality trait would you like to change?",
        "What's your favorite family tradition?",
        "What kept you up at night recently?",
        "What lifestyle would you love to try?",
        "What's your favorite weekend activity?",
        "When was your last scary moment?",
        "Which birthday would you love to relive?",
        "What's your favorite mode of transportation?",
        "What do you do to unwind?",
        "What habit would you like to change?",
        "What's your ideal vacation plan?",
        "What made you nervous recently?",
        "What cuisine would you love to try?",
        "What's your favorite shopping experience?",
        "What made you excited recently?"
      ],
      party: [
        "What's the craziest party game you've ever played?",
        "Tell us about the wildest party you've been to!",
        "What's your most embarrassing party moment?",
        "What's your go-to drink at parties?",
        "What's the craziest thing you've done while drunk?",
        "What's the weirdest theme party you've attended?",
        "Who's the most interesting stranger you've met at a party?",
        "What type of people do you love partying with?",
        "What's your ultimate party playlist?",
        "What's your worst party experience?",
        "What's your favorite party game?",
        "What's your biggest party no-no?",
        "What's your ideal party size?",
        "What party behavior makes you cringe?",
        "What's your favorite party snack?",
        "Do you hit on strangers at parties?",
        "What's the most expensive party you've been to?",
        "What's your favorite party theme?",
        "What makes or breaks a party?",
        "Do you dress up specially for parties?",
        "What's the best season for parties?",
        "What's the most creative party you've been to?",
        "What's your favorite party decoration style?",
        "What's a must-have drink at any party?",
        "What's your favorite way to party?",
        "What's your most memorable birthday party?",
        "What's the most awkward thing at parties?",
        "What's your favorite genre of party music?",
        "What's your most unique holiday party experience?",
        "What's the most important thing at a party?",
        "What's your ideal party venue?",
        "What's the most romantic party you've been to?",
        "What's your party dealbreaker?",
        "What's your favorite party game rule?",
        "What's the funniest party you've been to?",
        "What's the best thing about parties?",
        "How do you like to interact at parties?",
        "What's the most luxurious party you've attended?",
        "What's the perfect party vibe?",
        "How do you like parties to end?",
        "What's your favorite party role-play?",
        "What's the best costume party you've been to?",
        "What's your go-to truth or dare question?",
        "What's your favorite party costume theme?",
        "What's your best pool party story?",
        "What's the most thrilling party game you know?",
        "What's your must-have photo prop at parties?",
        "What's your craziest outdoor party story?",
        "What's the most romantic party moment you've had?",
        "What's your favorite party lighting setup?",
        "What's your best beach party memory?",
        "How do you break the ice at parties?",
        "What's your signature party dance move?",
        "What's your favorite camping party story?",
        "What's the best party surprise you've experienced?",
        "What's the coolest party prize you've won?",
        "What's your most epic BBQ party story?",
        "What's your favorite party activity?",
        "What's your go-to party photo spot?",
        "What's the best movie-themed party you've attended?",
        // New additions to reach 100
        "What's your favorite team party game?",
        "What party decorations always catch your eye?",
        "What's the best music party you've been to?",
        "What's your favorite interactive party game?",
        "What's your signature party pose?",
        "What's your best food party experience?",
        "What dance always gets everyone moving?",
        "What's your essential party game prop?",
        "What's the most artistic party you've attended?",
        "What's your favorite team-building party activity?",
        "What's your go-to party photo filter?",
        "What's your best sports-themed party story?",
        "What's your favorite ice-breaker game?",
        "What party theme always works?",
        "What's your best DIY party experience?",
        "What's your favorite cooperative party game?",
        "What's your best party photo angle?",
        "What's the coolest tech-themed party you've been to?",
        "What's your favorite party challenge?",
        "What's your go-to party mixer game?",
        "What's your favorite karaoke party song?",
        "What's the best surprise party you've planned?",
        "What's your favorite party drinking game?",
        "What's your best costume party win?",
        "What's your favorite party ice sculpture story?",
        "What's the most unique party entrance you've made?",
        "What's your favorite party tradition?",
        "What's the best party trick you've seen?",
        "What's your favorite party food combination?",
        "What's your most successful party hosting tip?",
        "What's your favorite party countdown moment?",
        "What's the best party cleanup story?",
        "What's your favorite party guest contribution?",
        "What's your best party planning hack?",
        "What's your favorite party mistake story?",
        "What's your go-to party recovery food?",
        "What's your favorite morning-after party story?",
        "What's your best party networking success?",
        "What's your favorite party group photo pose?",
        "What's your best party invitation story?"
      ],
      spicy: [
        "What's your biggest secret?",
        "What's something you never want others to find out about?",
        "What's the most rebellious thing you've ever done?",
        "What's your guilty pleasure that no one knows about?",
        "What's your craziest one-night stand story?",
        "What's the most outrageous thing you've ever done?",
        "What's the weirdest confession of love you've received?",
        "What's your most embarrassing dating story?",
        "What's the biggest lie you've ever told?",
        "What's your most regrettable decision?",
        "What's a memory you wish you could forget?",
        "What's your biggest fear in life?",
        "Who's someone you wish you could forget?",
        "What reality are you trying to avoid facing?",
        "Which relationship do you wish you could get back?",
        "What's something you'd never tell your parents?",
        "What responsibility are you trying to escape from?",
        "What's your biggest flaw that you won't admit to?",
        "Who do you want revenge on and why?",
        "What decision do you wish you could take back?",
        "What's your wildest adventure story?",
        "What's the boldest decision you've ever made?",
        "What limit are you dying to push?",
        "What's something you're scared to try but really want to?",
        "What personal boundary are you tempted to cross?",
        "What's the most unexpected thing you've done?",
        "What taboo are you curious about breaking?",
        "What's the craziest experience you want to try?",
        "What's your biggest risk-taking moment?",
        "What mental block are you trying to overcome?",
        "What's the most surprising thing you've done?",
        "What fear are you challenging yourself to face?",
        "What's something you need to face but keep avoiding?",
        "What comfort zone are you ready to leave?",
        "What's the most shocking thing you've done?",
        "What personal limit are you pushing?",
        "What thought are you afraid to voice?",
        "What social boundary do you want to push?",
        "What's the most unexpected decision you've made?",
        "What life goal seems too crazy to attempt?",
        "What social fear are you trying to overcome?",
        "What's something you did that still makes you nervous?",
        "What taboo are you curious about?",
        "What's something you're afraid to try but dream about?",
        "What extreme sport would you secretly love to try?",
        "What's the most spontaneous decision you've made?",
        "What self-imposed limit do you want to break?",
        "What truth are you afraid to face?",
        "What life goal seems impossible but excites you?",
        "What's your craziest adventure story?",
        "What mental barrier are you trying to break?",
        "What secret are you afraid to admit?",
        "What career move seems too risky but tempting?",
        "What's your boldest confession of love?",
        "What lifestyle change seems too radical to try?",
        "What relationship are you afraid to confront?",
        "What personal breakthrough are you working towards?",
        "What's your wildest travel story?",
        "What personality trait do you want to change?",
        "What experience scares you the most?",
        "What social taboo are you curious about?",
        "What's something that still makes you blush?",
        "What moral line have you considered crossing?",
        "What type of relationship scares you most?",
        "What interpersonal boundary do you want to push?",
        "What's your biggest act of rebellion?",
        "What social norm do you want to challenge?",
        "What emotion are you afraid to face?",
        "What self-perception do you want to challenge?",
        "What's your biggest escape story?",
        "What traditional belief do you want to question?",
        "What feeling are you afraid to admit?",
        "What social role do you want to challenge?",
        "What's your boldest act of defiance?",
        "What family rule do you want to break?",
        "What desire are you afraid to face?",
        "What value do you want to question?",
        "What's your wildest moment of letting loose?",
        "What mindset do you want to break free from?",
        "What emotion are you afraid to express?",
        "What social standard do you want to defy?",
        "What's your most daring form of expression?",
        "What gender role do you want to challenge?",
        "What temptation are you afraid to face?",
        "What moral belief do you question?",
        "What's your craziest challenge story?",
        "What identity constraint do you want to break?",
        "What thought are you afraid to acknowledge?",
        "What social expectation do you want to defy?",
        "What's your boldest experiment?",
        "What cultural taboo intrigues you?",
        "What impulse are you afraid to face?",
        "What behavioral norm do you want to challenge?",
        "What's your craziest decision story?",
        "What social barrier do you want to break?",
        "What desire are you afraid to express?",
        "What life taboo are you curious about?",
        "What's your most outrageous adventure?",
        "What self-limitation do you want to overcome?",
        "What challenge are you afraid to face?",
        "What boundary are you curious about testing?",
        "What's your most shocking confession?",
        "What rule do you secretly want to break?",
        "What wild experience calls to you?"
      ],
      mixed: [
        "If you could time travel, which era would you visit?",
        "What are your top 3 wishes in life?",
        "Which life decision would you change if you could?",
        "If you could only take 3 items to a deserted island, what would they be?",
        "Who are you most grateful for and why?",
        "If you could choose a superpower, what would it be?",
        "Which historical figure would you want to have dinner with?",
        "If you could switch careers right now, what would you choose?",
        "What are your top 3 dream travel destinations?",
        "If you could turn into any animal, what would you be?",
        "What extreme sport would you love to try?",
        "If you could instantly master one skill, what would it be?",
        "What's your dream lifestyle?",
        "If you could date any celebrity, who would it be?",
        "What's your biggest life goal?",
        "If you could stay one age forever, how old would you be?",
        "What aspect of the world would you most want to change?",
        "If you could choose where to be born, where would it be?",
        "What life experience are you most eager to have?",
        "If you could have any natural talent, what would you choose?",
        "If you had one superpower, what would you pick?",
        "What would you tell your past self if you could?",
        "Which historical event would you change if possible?",
        "If you could stay young forever, at what age?",
        "Which language would you instantly want to master?",
        "If you could talk to any animal, which would you choose?",
        "Where would you teleport to right now if you could?",
        "What special ability would you want to have?",
        "Which past decision would you most want to change?",
        "Which famous person would you want to have dinner with?",
        "What kind of lifestyle would you choose if you could?",
        "If you could keep one emotion forever, which would it be?",
        "Which era would you choose to live in?",
        "What unique power would you want to possess?",
        "What's one thing you'd change about your life?",
        "What dream job would you choose if you could?",
        "What moment would you want to remember forever?",
        "Where would you choose to settle down if you could live anywhere?",
        "Which habit would you most want to change?",
        "What kind of life would you choose if anything was possible?",
        "If you could have any talent, what would you pick?",
        "What would you ask your future self?",
        "Which life choice would you make differently?",
        "What state of being would you want to maintain forever?",
        "What field would you want to instantly become an expert in?",
        "Which fictional character would you want to talk to?",
        "Where would you spend a year traveling if you could go anywhere?",
        "What pace of life would you choose if you could?",
        "Which personality trait would you change if you could?",
        "Which historical person would you want to meet?",
        "What work style would be ideal for you?",
        "What skill would you want to keep forever?",
        "Which era's technology would you want to experience?",
        "What unique experience would you want to have?",
        "Which habit would you most want to break?",
        "What living environment would be perfect for you?",
        "What moment would you want to capture forever?",
        "What would be your ideal job if anything was possible?",
        "Which decision would you remake if you could?",
        "What life experience would you choose if you could have any?",
        "If you could master any musical instrument instantly, which would you choose?",
        "What would you do if you had unlimited money for 24 hours?",
        "If you could be famous for one thing, what would it be?",
        "What would your perfect day look like if you could plan it?",
        "If you could instantly learn any subject, what would you pick?",
        "What would you do differently if you knew no one would judge you?",
        "If you could live in any fictional world, where would you choose?",
        "What would your superhero name and power be?",
        "If you could master any sport instantly, which would you pick?",
        "What would you do if you could pause time for a day?",
        "If you could change one thing about society, what would it be?",
        "What would your dream house look like if money wasn't an issue?",
        "If you could instantly become fluent in any skill, what would you choose?",
        "What would you do if you could read minds for a day?",
        "If you could have dinner with any three people, who would they be?",
        "What would your ideal career path look like with no limitations?",
        "If you could master any form of art instantly, what would you choose?",
        "What would you do if you could control the weather?",
        "If you could live anywhere in the universe, where would you choose?",
        "What would your perfect vacation look like?",
        "If you could instantly gain any knowledge, what field would you choose?",
        "What would you do if you could fly for a day?",
        "If you could create any invention, what would it be?",
        "What would your life motto be if you had to choose one?",
        "If you could master any cooking style, which would you pick?",
        "What would you do if you could breathe underwater?",
        "If you could start any business with guaranteed success, what would it be?",
        "What would your dream adventure look like?",
        "If you could instantly learn any dance style, which would you choose?",
        "What would you do if you could talk to plants?",
        "If you could design your own holiday, what would it celebrate?",
        "What would your dream festival look like?",
        "If you could create any new sport, what would it be?",
        "What would you do if you could shrink to any size?",
        "If you could instantly master any technology, what would you choose?",
        "What would your perfect community look like?",
        "If you could create any new tradition, what would it be?",
        "What would you do if you could communicate with aliens?",
        "If you could design your own planet, what would it be like?",
        "What would your ultimate bucket list adventure be?"
      ]
}

interface GameInterfaceProps {
  mode: 'normal' | 'party' | 'spicy' | 'mixed'
}

export default function GameInterface({ mode }: GameInterfaceProps) {
  const [currentQuestion, setCurrentQuestion] = useState('')
  const [usedQuestions, setUsedQuestions] = useState<Set<string>>(new Set())
  const [isAnimating, setIsAnimating] = useState(false)
  const modeQuestions = useMemo(() => questions[mode], [mode])

  const getRandomQuestion = useCallback(() => {
    if (isAnimating) return // 防止动画过程中重复点击
    
    setIsAnimating(true)

    const availableQuestions = modeQuestions.filter(q => !usedQuestions.has(q))

    if (availableQuestions.length === 0) {
      setUsedQuestions(new Set())
      const randomQuestion = modeQuestions[Math.floor(Math.random() * modeQuestions.length)]
      setCurrentQuestion(randomQuestion)
      setUsedQuestions(new Set([randomQuestion]))
    } else {
      const randomQuestion = availableQuestions[Math.floor(Math.random() * availableQuestions.length)]
      setCurrentQuestion(randomQuestion)
      setUsedQuestions(prev => new Set([...prev, randomQuestion]))
    }

    setTimeout(() => {
      setIsAnimating(false)
    }, 500)
  }, [modeQuestions, usedQuestions, isAnimating])

  useEffect(() => {
    if (!currentQuestion) {
      const initialQuestion = modeQuestions[Math.floor(Math.random() * modeQuestions.length)]
      setCurrentQuestion(initialQuestion)
      setUsedQuestions(new Set([initialQuestion]))
    }
  }, [modeQuestions, currentQuestion])

  return (
    <div className="container mx-auto px-4 py-8">
      <motion.div 
        className="w-full aspect-[16/9] bg-purple-900/40 rounded-xl flex items-center justify-center p-8 mb-8 cursor-pointer hover:bg-purple-900/50 transition-colors"
        animate={isAnimating ? { scale: [1, 1.02, 1] } : {}}
        transition={{ duration: 0.5 }}
        onClick={getRandomQuestion}
      >
        <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-center select-none">
          {currentQuestion}
        </h2>
      </motion.div>


      {/* <div className="text-center mt-4 text-gray-400">
        Questions Asked:: {usedQuestions.size} / {modeQuestions.length}
      </div> */}
    </div>
  )
} 